### ISSUE TITLE
auto gen drill and gerber files

### ISSUE THREAD

**Issue by fgaletsee** [fgaletsee/RFLego#16]
*   generate drill and gerber files from all *.pcb_new files in folder "RFmodules"
 *   generated files in folder "FinalGerber" with same folder structure
 *   rename files according to /Tools/gerberrename.py
 *   generate pdf (optional)

**Comment by elnappo** [comment]
Fixed in https://github.com/fgaletsee/RFLego/commit/ca3b110c689ccf8ab24f06507f95075af202df6f
