### ISSUE TITLE
Noise source

### ISSUE THREAD

**Issue by fgaletsee** [fgaletsee/RFLego#17]
![rauschquelle](https://user-images.githubusercontent.com/6569156/51620162-13a64380-1f32-11e9-97fb-d89fb527e973.PNG)

http://www.df9ic.de/doc/2011/dorsten_2011/dorsten11_rauschquellen.pdf

**Comment by elnappo** [comment]
Fixed in https://github.com/fgaletsee/RFLego/commit/336eefedfd1e5d7e4f34a21880ea46777365ea59
