### ISSUE TITLE
Band Reject Filter

### ISSUE THREAD

**Issue by fgaletsee** [fgaletsee/RFLego#4]
We need a Band Reject Filter!
![screenshot_2018-12-18_09-13-57](https://user-images.githubusercontent.com/6569156/50140518-4e6aeb00-02a5-11e9-9bd7-b728d4930e07.png)

Order 3 4 and 5
https://rf-tools.com/lc-filter/

**Comment by elnappo** [comment]
https://github.com/fgaletsee/RFLego/tree/master/RFmodules/Filter/BandstopFilter7Order
